### ISSUE TITLE
All CRUD functions for user login and admin

### ISSUE THREAD

**Issue by emmaskillen** [madsgillis/AnimalAdoptionDatingApp#31]

**Comment by aliciacurtis** [comment]
Users can be created on the site as of the completion of this issue: https://github.com/madsgillis/AnimalAdoptionDatingApp/issues/16

Other CRUD functions aren't necessary for users through the website, since users changing their password or deleting their accounts through the site aren't project requirements.

CRUD functions for the admin page will be handled in this issue: https://github.com/madsgillis/AnimalAdoptionDatingApp/issues/30

As such, I'm closing this issue as not planned, as no action is needed on it.
